name: flutter_application_1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_switch: ^0.3.2
  get: 4.6.5
  google_maps_flutter: ^2.1.12
  flutter_phone_direct_caller: ^2.1.1
  geolocator: ^9.0.1
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  cloud_firestore: ^3.4.3
  shared_preferences: ^2.0.15
  firebase_storage: ^10.3.7
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.2
  intl: ^0.17.0
  flutter_polyline_points: ^1.0.0

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - images/